language: python

install:
- pip install sphinx sphinx_rtd_theme mock recommonmark


script:
- sphinx-build -Wv docs/source docs/build/html

deploy:
# publish docs on push
- provider: pages
  skip_cleanup: true
  keep-history: false
  github_token: $GH_TOKEN
  #local_dir: build/html
  on:
    branch:  gh_pages #master
